name: TaskFlow CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/taskflow
      JWT_SECRET: github-actions-test-secret
      NODE_ENV: test

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: npx prisma generate

      - run: npm run build

  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: npm run build
        env:
          NEXT_PUBLIC_API_URL: http://localhost:5000/api